#!/bin/sh

set -x

INSTALL_LIBERTY=0

if [ "devstackstorletsliberty" = "$0" ];
then
    INSTALL_LIBERTY=1
fi

export INSTALL_LIBERTY

# See <https://github.com/openstack/storlets/blob/master/README.md>
apt-get update
apt-get install --yes python-tox python-nose git

# NOTE: this is somewhat hardcoded in strolets, use the same user as
# the swift runtime user
install --directory --owner vagrant --group vagrant --  /opt/ibm

# Minimun versio of sudo, see also
# <http://stackoverflow.com/a/4024263>

SUDO_VERSION_MIN="1.8.10p3"
SUDO_VERSION="$(sudo --version | awk '{print $NF; exit}')"

if dpkg --compare-versions "${SUDO_VERSION}" ge "${SUDO_VERSION}";
then
    sudo -i -u vagrant -- /vagrant/provision/provision_vagrant_devstackstorlets
else
    sudo --login --user vagrant -- /vagrant/provision/provision_vagrant_devstackstorlets
fi
